language: cpp

# Ubuntu 18.04 https://docs.travis-ci.com/user/reference/bionic
# NOTE: this project requires cmake >= 3.11
dist: bionic

compiler:
  - gcc
  - clang

# Just check if build success or not for now
script:
  - cd src
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
  - make -j

notifications:
  email: false

os:
  - linux
  - osx
